[tool.poetry]
name = "aurora-trade"
version = "0.1.0"
description = "A standalone simple trading system for retail trader"
authors = ["chrischen <chrischen@ignity.xyz>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
